### ISSUE TITLE
Error in `paletteer::paletteer_d()`:

### ISSUE THREAD

**Issue by liamxg** [m-clark/NineteenEightyR#2]
Dear @m-clark,

Please see below:
<img width="1067" alt="image" src="https://github.com/m-clark/NineteenEightyR/assets/46078579/72247980-8c0c-4de8-997a-5d005082fb21">

**Comment by m-clark** [comment]
Hi @liamxg. It appears you are using the paletter_d function incorrectly in that example.

The following follows the documentation, and works fine for me without even explicitly loading this package.  Let me know if you have further issues.

```r
paletteer::paletteer_d('NineteenEightyR::sonny')
```
